
project_id = "xikmmkpfvshqncwmrpir"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[auth.email]
enabled = true

[auth.anonymous]
enabled = true

[functions.razorpay-webhook]
verify_jwt = false
